### ISSUE TITLE
url not showing up

### ISSUE THREAD

**Issue by leggomyinfo** [code4recovery/airtable-json#5]
@joshreisner We started passing `url` as a field in the SYNC_tsml view and several records have values (e.g. [https://www.anythingispossiblesf.org/](https://www.anythingispossiblesf.org/) for [https://aasfmarin.org/meetings?meeting=anything-is-possible-72](https://aasfmarin.org/meetings?meeting=anything-is-possible-72)). I was expecting to see a link somewhere to the meeting's website but nothing yet. I checked Meeting Guide too. Any ideas?

**Comment by joshreisner** [comment]
this isn't the right use of URL. from the spec, `url` is optional and should point to the meeting's listing on the area website

I should add this key but the values will be eg https://aasfmarin.org/meetings?meeting=mid-morning-support-118
